import Head from 'next/head'
import Home from '../src/components/Home.js'
import Image from 'next/image'
import Header from "../src/components/Header";

// import styles from '../styles/Home.module.scss'

// import Hero from '../.next/src/components/Hero'

export default function HomePage() {
  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={''}>
        <Home />
      </main>

      <footer>
        Footer
      </footer>
    </div>
  )
}
