import Head from 'next/head'
import Image from 'next/image'
import Header from "../src/components/Header";

// import styles from '../styles/Home.module.scss'

// import Hero from '../.next/src/components/Hero'

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={''}>
        <h1>Home Page</h1>
        <section id="contact">
          <h3 className="section-title">Contact Us</h3>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>


          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>

          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
          <p className="section-body">
            You can Contact us via our various social media handles
          </p>
        </section>
      </main>

      <footer>
        Footer
      </footer>
    </div>
  )
}
